### ISSUE TITLE
No Printer Found 

### ISSUE THREAD

**Issue by Sourovahmad** [rawilk/laravel-printing#24] opened 2021-06-26 07:52 UTC
I have installed the package and Printnode. Set the api but when i do

print_r(Printing::printers());

Array is empty

Please Help ... thanks

**Comment by Deyjandi** [comment] 2021-12-08 21:34
I have the same problem using the printnode driver.

**Comment by rawilk** [comment] 2022-02-10 14:19
Duplicate of #13 and #18.

**Closed by rawilk** 2022-02-10 14:19 UTC
Labels: bug
